dist: trusty
language: ruby
bundler_args: --without development
matrix:
  include:
    - rvm: 2.4
      env: DB=mariadb10.0
      addons:
        mariadb: 10.0
        hosts:
          - mysql2gem.example.com
    - rvm: 2.4
      env: DB=mariadb10.1
      addons:
        mariadb: 10.1
        hosts:
          - mysql2gem.example.com
    - rvm: 2.4
      env: DB=mariadb10.2
      addons:
        mariadb: 10.2
        hosts:
          - mysql2gem.example.com
    - rvm: 2.4
      env: DB=mariadb10.3
      addons:
        mariadb: 10.3
        hosts:
          - mysql2gem.example.com
    - rvm: 2.4
      env: DB=mysql55
      addons:
        hosts:
          - mysql2gem.example.com
  fast_finish: true
  allow_failures:
    # Allow failure due to a package repository not found for now.
    # https://travis-ci.org/github/brianmario/mysql2/jobs/767276558#L1255
    - env: DB=mysql55
